; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:wemos_d1_mini32]
platform = espressif32
board = wemos_d1_mini32
framework = arduino
monitor_speed = 115200
; upload_protocol = espota
; upload_port = 192.168.1.196
; upload_flags =
;     --port=3232

; Indique à PlatformIO quel filesystem utiliser pour uploadfs
board_build.filesystem = littlefs

; Active OTA + Wi-Fi debug + mDNS
build_flags =
    -DCORE_DEBUG_LEVEL=3

lib_deps =
  ESP32Async/AsyncTCP
  ESP32Async/ESPAsyncWebServer
  bblanchon/ArduinoJson

[env:wemos_d1_mini32_ota]
platform = ${env:wemos_d1_mini32.platform}
board = ${env:wemos_d1_mini32.board}
framework = ${env:wemos_d1_mini32.framework}
monitor_speed = ${env:wemos_d1_mini32.monitor_speed}
board_build.filesystem = ${env:wemos_d1_mini32.board_build.filesystem}
build_flags = ${env:wemos_d1_mini32.build_flags}
lib_deps = ${env:wemos_d1_mini32.lib_deps}

; Configurez l'IP du device (ou son hostname) pour l'upload OTA via PlatformIO
upload_protocol = espota
upload_port = 192.168.1.196
upload_flags =
    --port=3232
